server:
  port: 8000
spring:
  application:
    name: springcloud_eureka   #应用名称
eureka:
   client:
      #register-with-eureka: false   #是否将自己注册到Eureka Server     默认true
      #fetch-registry: false       #是否从Eureka Server 获取注册信息    默认true
      service-url: 
         defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/