server:
  port: 8010  #端口号
spring:
  application:
    name: springcloud-customer   #应用名称
  cloud:
    service-registry:
      auto-registration:
        enabled: true   #true 注册到Eureka Server false-不注册
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8000/eureka/  #Eureka Server 注册服务地址
  instance:
    prefer-ip-address: true   #将自己的IP注册到Eureka Server
